name: Sample App Tests

on: push

jobs:
  sample_app_tests:
    name: Run Tests Using Jest
    runs-on: ubuntu-lastest
    steps:
      - users: actions/checkout@v6
      
      - name: Install dependencies
        working-directory: sample-app
        run: npm install

      - name: Run tests
        working-directory: sample-app
        run: npm install